{
 "title": "grafana graphiques",
 "time": { "from": "2020-12-12T00:39:58.380Z", "to": "2021-02-21T09:51:30.477Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM country_vaccinations\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "nombre de vaccins utilisés",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  vaccines AS metric,\n  daily_vaccinations\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  },
  {
   "title": "people vaccinated by country",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_fully_vaccinated\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  },
  {
   "title": "vacination",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  }
 ]
}